class FieldError(Exception):
    def __init__(self):
        pass

class UserAlreadyExistsError(Exception):
    def __init__(self):
        pass